import json
import re
from pathlib import Path
from typing import Any

from app.core.config import Settings


class WebsiteGenerator:
    def __init__(self, settings: Settings):
        self.settings = settings

    async def generate_site(self, *, run_id: str, business: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
        business_name = business.get("name", "Generated Business")
        analysis = business.get("analysis", {})
        site_slug = self._slugify(business_name)
        site_dir = self.settings.generated_sites_dir / run_id / site_slug
        site_dir.mkdir(parents=True, exist_ok=True)

        files = {
            site_dir / "index.html": self._index_html(business, analysis, config),
            site_dir / "style.css": self._globals_css(config),
            site_dir / "README.md": self._readme(business_name),
        }

        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

        return {
            "businessName": business_name,
            "slug": site_slug,
            "path": str(site_dir),
            "files": [str(path.relative_to(site_dir)) for path in files],
            "theme": config.get("theme", "sunrise-studio"),
        }

    def _index_html(self, business: dict[str, Any], analysis: dict[str, Any], config: dict[str, Any]) -> str:
        name = business.get("name", "Local Business")
        address = business.get("address", "Serving the local area")
        phone = business.get("phone", "")
        website = business.get("website", "")
        hero_headline = analysis.get("hero_headline", name)
        hero_subheadline = analysis.get("hero_subheadline", "Professional service, local trust, and a clear next step.")
        description = analysis.get("description", "A polished starter site generated from workflow results.")
        services = analysis.get("services", ["Consultation", "Core service", "Support"])
        ctas = analysis.get("calls_to_action", ["Book a call", "Request a quote"])
        sections = analysis.get("website_sections", ["Services", "Why Choose Us", "Contact"])
        include_contact = config.get("includeContactForm", True)

        services_html = "".join([f'<article class="card"><h3>{s}</h3><p>Adapt this section with pricing and local proof.</p></article>' for s in services])
        ctas_html = "".join([f'<a class="button-primary" href="#contact">{c}</a>' for c in ctas])
        tags_html = "".join([f'<span class="tag">{s}</span>' for s in sections])

        contact_html = ""
        if include_contact:
            contact_html = """
            <section id="contact" class="panel contact-form">
                <div>
                    <p class="label">Contact</p>
                    <h2>Turn this generated draft into a live site fast.</h2>
                </div>
                <form onsubmit="event.preventDefault(); alert('Form submitted!');">
                    <input placeholder="Your name" />
                    <input placeholder="Email address" />
                    <textarea placeholder="Tell us what you need" rows="5"></textarea>
                    <button type="submit" class="button-primary">Send inquiry</button>
                </form>
            </section>
            """

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name}</title>
    <link rel="stylesheet" href="style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Instrument+Serif&family=Sora:wght@400;600&display=swap" rel="stylesheet">
</head>
<body>
    <main class="site-shell">
        <section class="hero">
            <p class="eyebrow">Generated by ScrapeFlow</p>
            <h1>{hero_headline}</h1>
            <p class="lede">{hero_subheadline}</p>
            <div class="hero-actions">
                {ctas_html}
            </div>
        </section>

        <section class="panel about-grid">
            <div>
                <p class="label">About</p>
                <h2>{name}</h2>
                <p>{description}</p>
            </div>
            <div class="contact-card">
                <p><strong>Address:</strong> {address}</p>
                <p><strong>Phone:</strong> {phone or 'Add phone number'}</p>
                <p><strong>Website:</strong> {website or 'Add official website'}</p>
            </div>
        </section>

        <section class="panel">
            <p class="label">Core services</p>
            <div class="grid">
                {services_html}
            </div>
        </section>

        <section class="panel">
            <p class="label">Recommended sections</p>
            <div class="tag-row">
                {tags_html}
            </div>
        </section>

        {contact_html}
    </main>
</body>
</html>"""

    def _globals_css(self, config: dict[str, Any]) -> str:
        theme = config.get("theme", "sunrise-studio")
        return f""":root {{
  --bg: #f7f1e7;
  --panel: #fff8ee;
  --ink: #1d1a17;
  --muted: #6b6258;
  --accent: #d35b2d;
  --accent-soft: #f6c7a4;
  --ring: rgba(211, 91, 45, 0.18);
  --theme-name: "{theme}";
}}

* {{
  box-sizing: border-box;
}}

html, body {{
  margin: 0;
  padding: 0;
  font-family: "Sora", system-ui, sans-serif;
  background:
    radial-gradient(circle at top left, rgba(246, 199, 164, 0.65), transparent 35%),
    linear-gradient(180deg, #fff9ef, #f2eadf);
  color: var(--ink);
  scroll-behavior: smooth;
}}

h1, h2, h3 {{
    font-family: "Instrument Serif", Georgia, serif;
    font-weight: 400;
}}

body {{
  min-height: 100vh;
}}

a {{
  color: inherit;
  text-decoration: none;
}}

input,
textarea {{
  width: 100%;
  border-radius: 16px;
  border: 1px solid rgba(29, 26, 23, 0.12);
  padding: 0.95rem 1rem;
  font: inherit;
  background: white;
}}

.site-shell {{
  width: min(1100px, calc(100% - 2rem));
  margin: 0 auto;
  padding: 3rem 0 5rem;
}}

.hero,
.panel {{
  background: rgba(255, 248, 238, 0.86);
  border: 1px solid rgba(29, 26, 23, 0.08);
  border-radius: 28px;
  padding: 2rem;
  box-shadow: 0 24px 60px rgba(41, 27, 14, 0.08);
  backdrop-filter: blur(14px);
  margin-bottom: 2rem;
}}

.about-grid {{
    display: grid;
    grid-template-columns: 1fr 340px;
    gap: 2rem;
    align-items: start;
}}

.hero {{
  margin-bottom: 1.5rem;
}}

.hero h1 {{
  margin: 0 0 0.75rem;
  letter-spacing: -0.04em;
  font-size: clamp(2.8rem, 6vw, 5.5rem);
  line-height: 0.95;
}}

.panel h2,
.card h3 {{
  margin: 0 0 0.75rem;
  letter-spacing: -0.04em;
  line-height: 1.1;
}}

.panel h2 {{ font-size: 3rem; }}
.card h3 {{ font-size: 1.75rem; }}

.lede,
.panel p {{
  color: var(--muted);
  line-height: 1.65;
}}

.eyebrow,
.label {{
  text-transform: uppercase;
  letter-spacing: 0.18em;
  font-size: 0.72rem;
  font-weight: 600;
  color: var(--accent);
  margin-bottom: 1rem;
  display: block;
}}

.hero-actions,
.tag-row {{
  display: flex;
  gap: 0.75rem;
  flex-wrap: wrap;
  margin-top: 1.5rem;
}}

.button-primary {{
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.9rem 1.75rem;
  border-radius: 999px;
  background: var(--accent);
  color: white;
  font-weight: 600;
  transition: transform 0.2s;
  border: none;
  cursor: pointer;
}}

.button-primary:hover {{
    transform: scale(1.02);
}}

.grid {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
}}

.card,
.contact-card {{
  background: white;
  border-radius: 22px;
  padding: 1.5rem;
  border: 1px solid rgba(29, 26, 23, 0.08);
}}

.tag {{
  border-radius: 999px;
  background: var(--accent-soft);
  padding: 0.65rem 1.25rem;
  font-weight: 600;
  font-size: 0.85rem;
}}

.contact-form form {{
  display: grid;
  gap: 1rem;
  margin-top: 1.5rem;
}}

@media (max-width: 900px) {{
    .about-grid {{
        grid-template-columns: 1fr;
    }}
}}

@media (max-width: 720px) {{
  .site-shell {{
    width: min(100% - 1.5rem, 1100px);
    padding-top: 1.5rem;
  }}

  .hero,
  .panel {{
    border-radius: 24px;
    padding: 1.5rem;
  }}
}}
"""

    def _readme(self, business_name: str) -> str:
        return f"# {business_name}\n\nThis site was generated locally by ScrapeFlow.\n\n## Structure\n- `index.html`: Main page structure\n- `style.css`: Visual styling\n"

    def _slugify(self, value: str) -> str:
        return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "generated-site"
